export default {
  LOAD_SPRINTS: 'LOAD_SPRINTS',
  SPRINTS_LOADED: 'SPRINTS_LOADED',
  LOAD_SPRINT: 'LOAD_SPRINT',
  SPRINT_LOADED: 'SPRINT_LOADED',

  CREATE_SPRINT: 'CREATE_SPRINT',
  SPRINT_CREATED: 'SPRINT_CREATED',

  CREATE_ESTIMATION: 'CREATE_ESTIMATION',
  ESTIMATION_CREATED: 'ESTIMATION_CREATED',

  FINISH_STORY_VOTING: 'FINISH_STORY_VOTING',
  STORY_VOTING_FINISHED: 'STORY_VOTING_FINISHED',

  CAPTURE_STORY_UPDATE: 'CAPTURE_STORY_UPDATE',
  CAPTURE_ESTIMATION_UPDATE: 'CAPTURE_ESTIMATION_UPDATE',

  I_AM_SCRUM_MASTER: 'I_AM_SCRUM_MASTER',
  I_AM_DEVELOPER: 'I_AM_DEVELOPER',
};
