version: "3"

networks:
  myappnet:

services:
  app:
    build:
      context: .
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - "8800:8000"
      - "8810:8810"
    networks:
      - myappnet
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - app
    ports:
      - "3000:3000"
    networks:
      - myappnet
  mongo:
    container_name: scrum-poker-mongo
    healthcheck:
      test: mongostat -n1
      retries: 5
      timeout: 10s
      interval: 10s
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - myappnet
