version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: pinad-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"